# Generated by Django 5.1 on 2024-08-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePortalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("icon", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="HomePortalApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=255)),
                ("link_name", models.CharField(max_length=30)),
                ("link", models.CharField(max_length=255)),
                ("side_menu_visible", models.BooleanField(default=False)),
                ("nav_link_visible", models.BooleanField(default=False)),
                ("side_menu_name", models.CharField(default="", max_length=30)),
                ("side_menu_icon", models.CharField(default="", max_length=30)),
                ("nav_link_name", models.CharField(default="", max_length=30)),
                ("nav_link_icon", models.CharField(default="", max_length=30)),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.homeportalcategory",
                    ),
                ),
            ],
        ),
    ]
