services:
  home-portal-postgres-16:
    container_name: hp-postgres-16
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_USER: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - home-portal-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1028M

  home-portal-pgadmin-8:
    container_name: hp-pgadmin-8
    image: dpage/pgadmin4:8.5
    restart: always
    env_file:
      - .env
    environment:
      - SCRIPT_NAME=/pgadmin
    networks:
      - home-portal-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1028M

  home-portal-admin:
    container_name: hp-admin
    image: ghcr.io/evanlab02/hp-admin:v0.2.0
    env_file:
      - .env
    depends_on:
      home-portal-postgres-16:
        condition: service_healthy
    restart: always
    networks:
      - home-portal-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    command: "/bin/bash -c 'python manage.py migrate && uvicorn hub.admin.asgi:application --host 0.0.0.0 --port 80 --workers 1'"

  home-portal-api:
    container_name: hp-api
    image: ghcr.io/evanlab02/hp-api:v0.2.0
    env_file:
      - .env
    depends_on:
      home-portal-postgres-16:
        condition: service_healthy
    restart: always
    networks:
      - home-portal-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  home-portal-site:
    container_name: hp-site
    image: ghcr.io/evanlab02/hp-site:v0.2.0
    env_file:
      - .env
    restart: always
    expose:
      - 80
      - 9999
    ports:
      - "80:80"
      - "9999:9999"
    networks:
      - home-portal-network
    volumes:
      - ./site/Caddyfile:/etc/caddy/Caddyfile
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  shopping-django-administration:
    container_name: shopping-django-admin
    image: ghcr.io/evanlab02/shoppingappadmin:0.16.2
    env_file:
      - .env
    environment:
      SHOPPING_DEFAULT_SETTINGS_MODULE: shoppingapp.settings.settings
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver"
    depends_on:
      home-portal-postgres-16:
        condition: service_healthy
    networks:
      - home-portal-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  shopping-django-app:
    container_name: shopping-django-app
    image: ghcr.io/evanlab02/shoppingappbe:0.16.2
    environment:
      SHOPPING_DEFAULT_SETTINGS_MODULE: shoppingapp.settings.settings
    env_file:
      - .env
    command: "gunicorn -b 0.0.0.0:80 -w 1 --log-config shoppingapp/logging.config --capture-output --log-level info --worker-class uvicorn_worker.UvicornWorker 'shoppingapp.config.asgi:app'"
    depends_on:
      home-portal-postgres-16:
        condition: service_healthy
    networks:
      - home-portal-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  postgres-data:
    external: false
  pgadmin-data:
    external: false

networks:
  home-portal-network:
    driver: bridge
