site_name: Home Portal Documentation

plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
theme:
  name: material
  features:
    - content.code.copy
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - First Steps: index.md
  - Guides:
    - Setting up: guides/index.md
    - Post setup: guides/post-setup.md
    - Setup PGAdmin: guides/pgadmin.md
    - Application Setup Guides:
      - Development Applications: apps/development.md
      - Shopping List App Application: apps/shopping-app.md
      - Plex Media Server Application: apps/plex.md
      - Prowlarr: apps/prowlarr.md
      - Radarr: apps/radarr.md
      - Sonarr: apps/sonarr.md
    - Update Guides:
      - V0.2.0: update/update0-2-0.md
