name: Frontend Checks

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./frontend

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Setup Github Packages Token
      working-directory: ./frontend
      run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PKG_KEY }} >> ~/.npmrc
    - name: Install Dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Run tests
      run: |
        npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Setup Github Packages Token
      working-directory: ./frontend
      run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PKG_KEY }} >> ~/.npmrc
    - name: Install Dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Linting
      run: |
        npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Setup Github Packages Token
      working-directory: ./frontend
      run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PKG_KEY }} >> ~/.npmrc
    - name: Install Dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Build
      run: |
        npm run build